name: Integration Tests
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

env:
  REACT_APP_NETWORK_URL: 'https://mainnet.infura.io/v3/1221fd11e90849509afafd330ec7acc6'
  APP_ID: 1

jobs:
  