name: PRaul
on:
  pull_request:
    types: [ opened, synchronize ]
jobs:
  publish-praul:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set environment variables
        run: |
          cat $GITHUB_EVENT_PATH
          echo "PULL_REQUEST=$(jq --raw-output .number "$GITHUB_EVENT_PATH")" >> $GITHUB_ENV
      - name: Run build script
        run: ./.github/scripts/deploy_pull_request.sh
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_GNOSIS_INFO_API_TOKEN: ${{ secrets.GITHUB_TOKEN }} #${{ secrets.GITHUB_GNOSIS_INFO_API_TOKEN }}
          AWS_ACCESS_KEY_ID: "dummy_key" #${{ secrets.AWS_ACCESS_KEY_ID }}
          REVIEW_BUCKET_NAME: "dummy_bucket" #${{ secrets.REVIEW_BUCKET_NAME }}
          REPO_SLUG: ${{ github.repository }}
